// Mixture configuration: the file that decides what goes into a corpus.
//
// The format is TOML, parsed by `toml.rs` (the repo carries no serde), so any
// editor's TOML support gives syntax checking as you type and the schema next
// door (`mixture.schema.json`, named by the `#:schema` line at the top of each
// mixture) gives key completion and unknown-key warnings. Four table kinds:
//
//   [output]          where the corpus goes and how big it is
//   [filter]          quality defaults, inherited by every source
//   [llm]             the local OpenAI-compatible server, for `kind = "llm"`
//                     sources and for `judge` filters
//   [source.NAME]     one input, its weight, and its filter overrides
//
// Every key is validated: an unknown one is an error naming the line, because
// a silently ignored filter is a corpus you cannot trust. So is a value of the
// wrong type — the schema catches those in the editor, this catches them in
// the file the editor never opened.
use std::collections::HashMap;
use std::fmt;

use crate::toml::{self, Value};

pub type Result<T> = std::result::Result<T, String>;

#[derive(Clone, Copy, PartialEq, Debug)]
pub enum OutKind {
    /// `{instruction, context, response, category}` JSONL — `src/sft.rs`.
    Sft,
    /// `<|endoftext|>`-separated plain text — `ChunkedWordDataSet`.
    Text,
    /// Analyze only; write the report, no corpus.
    None,
}

/// What a `weight` is a share of, and what the budget counts.
#[derive(Clone, Copy, PartialEq, Debug)]
pub enum WeightUnit {
    Tokens,
    /// One record (one Q-A example or conversation) counts as one, whatever its
    /// length. A corpus of short tool calls and long chats then mixes by how
    /// often each is *asked*, not by how much text it happens to carry.
    Records,
}

#[derive(Clone, Copy, PartialEq, Debug)]
pub enum Dedup {
    Off,
    /// Hash of the whitespace-normalized text: byte-identical duplicates.
    Exact,
    /// MinHash over 5-gram shingles: near-duplicates (boilerplate, forks).
    Near,
}

#[derive(Clone, Copy, PartialEq, Debug)]
pub enum SourceKind {
    /// One text file, optionally split on `<|endoftext|>`.
    File,
    /// Every file under a directory (recursive), one document per file.
    Dir,
    /// Parquet with a text column (and optionally a language column).
    Parquet,
    /// JSONL, one `{instruction, context, response, category}` record per line.
    Dolly,
    /// JSONL, one free-text field per line (`field` picks it, default `text`).
    Jsonl,
    /// Template expansion — see `synth.rs`.
    Synth,
    /// Generated by the local model — see `llm.rs`.
    Llm,
    /// Parquet whose messages column is a `list<struct<role, content>>` — the
    /// shape every chat corpus (SmolTalk, UltraChat, OpenHermes) ships in.
    Chat,
}

/// Quality gates. Every field is inherited from `[filter]` and may be
/// overridden per source.
#[derive(Clone)]
pub struct Filters {
    pub min_bytes: usize,
    pub max_bytes: usize,
    pub max_tokens: usize,
    pub min_words: usize,
    /// Cap on the **words** of one record — the unit the backbone unrolls in,
    /// and the one that has to match `SFT_MAX_WORDS` / `WORDS_PER_SEQ`. Counted
    /// with the model's own splitter (`wordseg`), so it means the same thing on
    /// both sides.
    pub max_words: usize,
    /// Minimum share of letters/digits — kills base64 blobs and binary dumps.
    pub min_alpha_ratio: f32,
    /// Maximum share of lines that are duplicates of an earlier line.
    pub max_dup_line_ratio: f32,
    /// Longest single line, in bytes — kills minified files.
    pub max_line_bytes: usize,
    pub must_contain: Vec<String>,
    pub must_not_contain: Vec<String>,
    pub dedup: Dedup,
    /// ISO codes kept from a parquet `language` column. Empty = no filtering.
    pub languages: Vec<String>,
    /// Prompt handed to the local model together with each record; the record
    /// is kept only when the reply starts with `judge_expect`. Empty = no
    /// judging (and no server needed).
    pub judge: String,
    pub judge_expect: String,
    /// Model and temperature for the judge alone. Judging is a classification,
    /// not a generation: it wants temperature 0 whatever the generator is set
    /// to, and it may be worth spending a stronger model on.
    pub judge_model: String,
    pub judge_temperature: f32,
    /// Trim a conversation to the last whole exchange that fits `max_tokens`
    /// instead of dropping it. Only affects `chat`-shaped records.
    pub trim_turns: bool,
}

impl Default for Filters {
    fn default() -> Self {
        Self {
            min_bytes: 1,
            max_bytes: usize::MAX,
            max_tokens: usize::MAX,
            min_words: 0,
            max_words: usize::MAX,
            min_alpha_ratio: 0.0,
            max_dup_line_ratio: 1.0,
            max_line_bytes: usize::MAX,
            must_contain: Vec::new(),
            must_not_contain: Vec::new(),
            dedup: Dedup::Off,
            languages: Vec::new(),
            judge: String::new(),
            judge_expect: "yes".to_string(),
            judge_model: String::new(),
            judge_temperature: 0.0,
            trim_turns: false,
        }
    }
}

#[derive(Clone)]
pub struct Source {
    pub name: String,
    pub kind: SourceKind,
    pub path: String,
    /// Share of the output this source gets, relative to the other weights.
    pub weight: f32,
    /// How often a source may be repeated to reach its share. `1` never
    /// upsamples; `3` lets a small high-value source be seen three times.
    pub epochs: f32,
    /// Extension filter for `dir` (without the dot). Empty = every file.
    pub ext: Vec<String>,
    /// `file`/`dir`: split each file on this separator into documents.
    pub separator: String,
    /// `dir`/`parquet` over a directory: skip this many files of the sorted
    /// listing. A corpus already trained on for N shards resumes at N.
    pub skip_files: usize,
    /// `dir`/`parquet` over a directory: read at most this many files after the
    /// skip. `0` = all of them.
    pub max_files: usize,
    /// Parquet/JSONL field names.
    pub text_column: String,
    pub language_column: String,
    /// `chat`: the leaves of the messages column, by name or dotted path.
    pub role_column: String,
    pub content_column: String,
    /// `chat`: keep only rows whose `select_column` holds one of
    /// `select_values`. A corpus of several subsets under one file — SmolTalk's
    /// `source` — is otherwise all-or-nothing, and its subsets differ by more
    /// than topic: answer length varies 10x between them.
    pub select_column: String,
    pub select_values: Vec<String>,
    /// `synth`/`llm`: how many examples to generate (`synth`: 0 = every
    /// combination).
    pub count: usize,
    /// `llm`: system prompt, user prompt, examples asked for per call, and an
    /// optional `.syn` file whose rendered instructions seed `{seed}` in the
    /// prompt so successive calls do not all ask the same thing.
    pub system: String,
    pub prompt: String,
    pub batch: usize,
    pub seed_file: String,
    /// `llm`: how many seed examples to render into `{seed}` per call. More
    /// seeds means more variety in one call and a firmer grip on the format.
    pub seeds: usize,
    /// `llm`: per-source overrides of `[llm] model` / `temperature`
    /// (`temperature < 0` = inherit).
    pub model: String,
    pub temperature: f32,
    /// Category tag written on SFT records that carry none of their own.
    pub category: String,
    pub filters: Filters,
}

pub struct Output {
    pub kind: OutKind,
    pub path: String,
    pub seed: u64,
    /// Unit the weights and the budget are counted in.
    pub weight_by: WeightUnit,
    /// Token budget. `0` = as much as the weights allow without truncating
    /// more of any source than its `epochs` permit.
    pub tokens: usize,
    /// Record budget, used instead of `tokens` when `weight_by = "records"`.
    pub records: usize,
    pub shuffle: bool,
    pub report: String,
    /// Fraction held out into `<path>.eval`. `0` = no holdout.
    pub holdout: f32,
    /// Split the text output into files of at most this many bytes. `0` = one file.
    pub shard_bytes: usize,
}

/// The local OpenAI-compatible server (LM Studio's default is
/// `http://localhost:1234/v1`). Only consulted by `kind = llm` sources and
/// `judge` filters, so a mixture that uses neither never opens a socket.
#[derive(Clone)]
pub struct Llm {
    pub endpoint: String,
    /// Model id as the server reports it. Empty lets a single-model server pick.
    pub model: String,
    pub temperature: f32,
    pub max_tokens: usize,
    /// Seconds to wait on one completion.
    pub timeout: usize,
    pub retries: usize,
    /// Directory of cached replies. Empty disables caching.
    pub cache: String,
    pub api_key: String,
}

impl Default for Llm {
    fn default() -> Self {
        Self {
            endpoint: "http://localhost:1234/v1".to_string(),
            model: String::new(),
            temperature: 0.8,
            max_tokens: 1024,
            timeout: 300,
            retries: 2,
            cache: "target/datamix-llm-cache".to_string(),
            api_key: String::new(),
        }
    }
}

pub struct Mix {
    pub output: Output,
    pub llm: Llm,
    pub sources: Vec<Source>,
}

pub fn load(path: &str) -> Result<Mix> {
    let text = std::fs::read_to_string(path).map_err(|e| format!("{path}: {e}"))?;
    parse(&text, path).map_err(|e| {
        // The pre-TOML format used `[source name]` headers and unquoted values.
        if text.contains("[source ") {
            format!("{e}\n(this looks like the old .dm format: headers are now [source.name] and string values are quoted)")
        } else {
            e
        }
    })
}

pub fn parse(text: &str, path: &str) -> Result<Mix> {
    let entries = toml::parse(text, path)?;

    let mut out_kv = Kv::new("output");
    let mut def_kv = Kv::new("filter");
    let mut llm_kv = Kv::new("llm");
    let mut sources: Vec<Kv> = Vec::new();

    for e in entries {
        let target = match e.table.as_slice() {
            [t] if t == "output" => &mut out_kv,
            [t] if t == "filter" => &mut def_kv,
            [t] if t == "llm" => &mut llm_kv,
            [t, name] if t == "source" => {
                if let Some(i) = sources.iter().position(|k| k.name == *name) {
                    &mut sources[i]
                } else {
                    sources.push(Kv::new(name));
                    sources.last_mut().unwrap()
                }
            }
            [t] if t == "source" => {
                return Err(format!(
                    "{path}:{}: [source] needs a name: [source.rust-std]",
                    e.line
                ));
            }
            other => {
                return Err(format!(
                    "{path}:{}: unknown table [{}]",
                    e.line,
                    other.join(".")
                ));
            }
        };
        target.set(e.key, e.value, e.line);
    }

    let defaults = filters_from(&def_kv, &Filters::default(), path)?;
    let output = output_from(&out_kv, path)?;
    let llm = llm_from(&llm_kv, path)?;

    let mut parsed = Vec::with_capacity(sources.len());
    for kv in &sources {
        parsed.push(source_from(kv, &defaults, path)?);
    }
    // Key validation first: a typo is a more useful error than the downstream
    // symptom it causes.
    out_kv.reject_unknown(path)?;
    def_kv.reject_unknown(path)?;
    llm_kv.reject_unknown(path)?;
    for kv in &sources {
        kv.reject_unknown(path)?;
    }
    if parsed.is_empty() && output.kind != OutKind::None {
        return Err(format!("{path}: no [source.NAME] tables"));
    }
    Ok(Mix {
        output,
        llm,
        sources: parsed,
    })
}

/// The keys of one section, with the line each came from (for error messages)
/// and a record of which were read — anything left over is a typo.
struct Kv {
    name: String,
    map: HashMap<String, (Value, usize)>,
    used: std::cell::RefCell<Vec<String>>,
}

impl Kv {
    fn new(name: &str) -> Self {
        Self {
            name: name.to_string(),
            map: HashMap::new(),
            used: std::cell::RefCell::new(Vec::new()),
        }
    }

    fn set(&mut self, k: String, v: Value, line: usize) {
        self.map.insert(k, (v, line));
    }

    fn get(&self, key: &str) -> Option<&(Value, usize)> {
        self.used.borrow_mut().push(key.to_string());
        self.map.get(key)
    }

    fn reject_unknown(&self, path: &str) -> Result<()> {
        let used = self.used.borrow();
        for (k, (_, line)) in &self.map {
            if !used.contains(k) {
                return Err(format!(
                    "{path}:{line}: unknown key '{k}' in table '{}'",
                    self.name
                ));
            }
        }
        Ok(())
    }

    fn wrong(&self, path: &str, key: &str, line: usize, want: &str, got: &Value) -> String {
        format!(
            "{path}:{line}: '{key}' in table '{}' expects {want}, got {} ({got})",
            self.name,
            got.type_name()
        )
    }

    fn str_opt(&self, key: &str, path: &str) -> Result<Option<String>> {
        match self.get(key) {
            None => Ok(None),
            Some((Value::Str(s), _)) => Ok(Some(s.clone())),
            Some((v, line)) => Err(self.wrong(path, key, *line, "a string", v)),
        }
    }

    fn str(&self, key: &str, default: &str, path: &str) -> Result<String> {
        Ok(self.str_opt(key, path)?.unwrap_or_else(|| default.to_string()))
    }

    /// An array of strings. A lone string counts as a one-element array, so
    /// `must_not_contain = "TODO"` needs no brackets.
    fn list(&self, key: &str, default: &[String], path: &str) -> Result<Vec<String>> {
        match self.get(key) {
            None => Ok(default.to_vec()),
            Some((Value::Str(s), _)) => Ok(vec![s.clone()]),
            Some((Value::Array(items), line)) => items
                .iter()
                .map(|v| match v {
                    Value::Str(s) => Ok(s.clone()),
                    other => Err(self.wrong(path, key, *line, "an array of strings", other)),
                })
                .collect(),
            Some((v, line)) => Err(self.wrong(path, key, *line, "an array of strings", v)),
        }
    }

    /// A count, either as an integer or as a suffixed string (`"400k"`).
    fn num(&self, key: &str, default: usize, path: &str) -> Result<usize> {
        match self.get(key) {
            None => Ok(default),
            Some((Value::Int(i), line)) => usize::try_from(*i)
                .map_err(|_| format!("{path}:{line}: '{key}' must not be negative")),
            Some((Value::Str(s), line)) => parse_size(s).ok_or_else(|| {
                format!("{path}:{line}: '{key}' is not a size: {s:?} (try 4096 or \"64k\")")
            }),
            Some((v, line)) => Err(self.wrong(path, key, *line, "a size", v)),
        }
    }

    fn float(&self, key: &str, default: f32, path: &str) -> Result<f32> {
        match self.get(key) {
            None => Ok(default),
            Some((Value::Float(x), _)) => Ok(*x as f32),
            Some((Value::Int(i), _)) => Ok(*i as f32),
            Some((v, line)) => Err(self.wrong(path, key, *line, "a number", v)),
        }
    }

    fn bool(&self, key: &str, default: bool, path: &str) -> Result<bool> {
        match self.get(key) {
            None => Ok(default),
            Some((Value::Bool(b), _)) => Ok(*b),
            Some((v, line)) => Err(self.wrong(path, key, *line, "true or false", v)),
        }
    }
}

/// `4096`, `64k`, `12M`, `3G`, `unlimited`. Sizes are bytes or tokens depending
/// on the key; the byte tokenizer makes those the same number anyway.
fn parse_size(v: &str) -> Option<usize> {
    let v = v.trim();
    if v.eq_ignore_ascii_case("unlimited") || v == "-" {
        return Some(usize::MAX);
    }
    let (digits, mult) = match v.as_bytes().last()? {
        b'k' | b'K' => (&v[..v.len() - 1], 1_000),
        b'm' | b'M' => (&v[..v.len() - 1], 1_000_000),
        b'g' | b'G' => (&v[..v.len() - 1], 1_000_000_000),
        _ => (v, 1),
    };
    digits
        .trim()
        .replace('_', "")
        .parse::<usize>()
        .ok()
        .map(|n| n.saturating_mul(mult))
}

fn output_from(kv: &Kv, path: &str) -> Result<Output> {
    let kind = match kv.str("kind", "sft", path)?.as_str() {
        "sft" => OutKind::Sft,
        "text" => OutKind::Text,
        "none" | "report" => OutKind::None,
        other => return Err(format!("{path}: output kind must be sft|text|none, got {other:?}")),
    };
    let weight_by = match kv.str("weight_by", "tokens", path)?.as_str() {
        "tokens" => WeightUnit::Tokens,
        "records" => WeightUnit::Records,
        other => {
            return Err(format!(
                "{path}: output weight_by must be tokens|records, got {other:?}"
            ));
        }
    };
    let default_path = if kind == OutKind::Text {
        "data/mix/out.txt"
    } else {
        "data/mix/out.jsonl"
    };
    Ok(Output {
        kind,
        path: kv.str("path", default_path, path)?,
        seed: kv.num("seed", 1234, path)? as u64,
        weight_by,
        tokens: kv.num("tokens", 0, path)?,
        records: kv.num("records", 0, path)?,
        shuffle: kv.bool("shuffle", true, path)?,
        report: kv.str("report", "", path)?,
        holdout: kv.float("holdout", 0.0, path)?,
        shard_bytes: kv.num("shard_bytes", 0, path)?,
    })
}

fn llm_from(kv: &Kv, path: &str) -> Result<Llm> {
    let d = Llm::default();
    Ok(Llm {
        endpoint: kv.str("endpoint", &d.endpoint, path)?,
        model: kv.str("model", &d.model, path)?,
        temperature: kv.float("temperature", d.temperature, path)?,
        max_tokens: kv.num("max_tokens", d.max_tokens, path)?,
        timeout: kv.num("timeout", d.timeout, path)?,
        retries: kv.num("retries", d.retries, path)?,
        cache: kv.str("cache", &d.cache, path)?,
        api_key: kv.str("api_key", &d.api_key, path)?,
    })
}

fn filters_from(kv: &Kv, base: &Filters, path: &str) -> Result<Filters> {
    let dedup = match kv
        .str(
            "dedup",
            match base.dedup {
                Dedup::Off => "off",
                Dedup::Exact => "exact",
                Dedup::Near => "near",
            },
            path,
        )?
        .as_str()
    {
        "off" | "none" => Dedup::Off,
        "exact" => Dedup::Exact,
        "near" | "fuzzy" => Dedup::Near,
        other => return Err(format!("{path}: dedup must be off|exact|near, got {other:?}")),
    };
    Ok(Filters {
        min_bytes: kv.num("min_bytes", base.min_bytes, path)?,
        max_bytes: kv.num("max_bytes", base.max_bytes, path)?,
        max_tokens: kv.num("max_tokens", base.max_tokens, path)?,
        min_words: kv.num("min_words", base.min_words, path)?,
        max_words: kv.num("max_words", base.max_words, path)?,
        min_alpha_ratio: kv.float("min_alpha_ratio", base.min_alpha_ratio, path)?,
        max_dup_line_ratio: kv.float("max_dup_line_ratio", base.max_dup_line_ratio, path)?,
        max_line_bytes: kv.num("max_line_bytes", base.max_line_bytes, path)?,
        must_contain: kv.list("must_contain", &base.must_contain, path)?,
        must_not_contain: kv.list("must_not_contain", &base.must_not_contain, path)?,
        dedup,
        languages: kv.list("languages", &base.languages, path)?,
        judge: kv.str("judge", &base.judge, path)?,
        judge_expect: kv.str("judge_expect", &base.judge_expect, path)?,
        judge_model: kv.str("judge_model", &base.judge_model, path)?,
        judge_temperature: kv.float("judge_temperature", base.judge_temperature, path)?,
        trim_turns: kv.bool("trim_turns", base.trim_turns, path)?,
    })
}

fn source_from(kv: &Kv, defaults: &Filters, path: &str) -> Result<Source> {
    let kind = match kv.str("kind", "", path)?.as_str() {
        "file" => SourceKind::File,
        "dir" => SourceKind::Dir,
        "parquet" => SourceKind::Parquet,
        "dolly" | "sft" => SourceKind::Dolly,
        "jsonl" => SourceKind::Jsonl,
        "synth" => SourceKind::Synth,
        "llm" | "generate" => SourceKind::Llm,
        "chat" | "chat_parquet" => SourceKind::Chat,
        "" => return Err(format!("{path}: [source {}] has no kind", kv.name)),
        other => {
            return Err(format!(
                "{path}: [source {}] unknown kind {other:?} \
                 (file|dir|parquet|chat|dolly|jsonl|synth|llm)",
                kv.name
            ));
        }
    };
    let src_path = kv.str("path", "", path)?;
    // An `llm` source generates from a prompt; every other kind reads a path.
    if src_path.is_empty() && kind != SourceKind::Llm {
        return Err(format!("{path}: [source {}] has no path", kv.name));
    }
    let prompt = kv.str("prompt", "", path)?;
    if kind == SourceKind::Llm && prompt.is_empty() {
        return Err(format!("{path}: [source {}] has no prompt", kv.name));
    }
    // Half a row filter keeps everything or nothing; either way it is a typo.
    let select_column = kv.str("select_column", "", path)?;
    let select_values = kv.list("select_values", &[], path)?;
    if select_column.is_empty() != select_values.is_empty() {
        return Err(format!(
            "{path}: [source {}] needs both select_column and select_values, or neither",
            kv.name
        ));
    }
    Ok(Source {
        name: kv.name.clone(),
        kind,
        path: src_path,
        weight: kv.float("weight", 1.0, path)?,
        epochs: kv.float("epochs", 1.0, path)?,
        ext: kv.list("ext", &[], path)?,
        separator: kv.str("separator", "<|endoftext|>", path)?,
        skip_files: kv.num("skip_files", 0, path)?,
        max_files: kv.num("max_files", 0, path)?,
        text_column: kv.str("text_column", "text", path)?,
        language_column: kv.str("language_column", "language", path)?,
        role_column: kv.str("role_column", "role", path)?,
        content_column: kv.str("content_column", "content", path)?,
        select_column,
        select_values,
        count: kv.num("count", 0, path)?,
        category: kv.str("category", &kv.name, path)?,
        system: kv.str("system", "", path)?,
        prompt: prompt,
        batch: kv.num("batch", 10, path)?.max(1),
        seed_file: kv.str("seed_file", "", path)?,
        seeds: kv.num("seeds", 3, path)?.max(1),
        model: kv.str("model", "", path)?,
        temperature: kv.float("temperature", -1.0, path)?,
        filters: filters_from(kv, defaults, path)?,
    })
}

impl fmt::Display for OutKind {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        f.write_str(match self {
            OutKind::Sft => "sft",
            OutKind::Text => "text",
            OutKind::None => "none",
        })
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    const MIX: &str = r#"
[output]
kind = "text"
path = "out.txt"
tokens = "12M"

[filter]
min_bytes = 100
dedup = "near"

[source.a]
kind = "dir"
path = "data/a"
ext = ["rs", "md"]
weight = 2

[source.b]
kind = "synth"
path = "b.syn"
min_bytes = 5
"#;

    #[test]
    fn parses_tables_and_inherits_filters() {
        let m = parse(MIX, "mix.toml").unwrap();
        assert_eq!(m.output.kind, OutKind::Text);
        assert_eq!(m.output.tokens, 12_000_000);
        assert_eq!(m.sources.len(), 2);
        assert_eq!(m.sources[0].ext, vec!["rs", "md"]);
        assert_eq!(m.sources[0].weight, 2.0);
        // inherited from [filter]
        assert_eq!(m.sources[0].filters.min_bytes, 100);
        assert_eq!(m.sources[0].filters.dedup, Dedup::Near);
        // overridden per source, without losing the other inherited keys
        assert_eq!(m.sources[1].filters.min_bytes, 5);
        assert_eq!(m.sources[1].filters.dedup, Dedup::Near);
    }

    #[test]
    fn unknown_key_is_an_error() {
        let err = parse("[output]\nkind = \"text\"\nkidn = \"sft\"\n", "mix.toml")
            .err()
            .unwrap();
        assert!(err.contains("unknown key 'kidn'"), "{err}");
        assert!(err.starts_with("mix.toml:3:"), "{err}");
    }

    #[test]
    fn unknown_table_is_an_error() {
        let err = parse("[filtre]\nmin_bytes = 1\n", "mix.toml").err().unwrap();
        assert!(err.contains("unknown table [filtre]"), "{err}");
    }

    /// The whole point of the type check: a wrong-typed value must not be
    /// silently coerced into something plausible.
    #[test]
    fn a_wrong_type_names_the_key_and_what_it_wanted() {
        let err = parse("[output]\nshuffle = 3\n", "mix.toml").err().unwrap();
        assert!(err.contains("'shuffle'") && err.contains("true or false"), "{err}");
        let err = parse("[source.a]\nkind = \"dir\"\npath = \"x\"\nweight = \"heavy\"\n", "mix.toml")
            .err()
            .unwrap();
        assert!(err.contains("'weight'") && err.contains("a number"), "{err}");
    }

    #[test]
    fn llm_table_and_judge_inherit() {
        let m = parse(
            r#"
[llm]
endpoint = "http://127.0.0.1:9000/v1"
model = "qwen"
temperature = 1.2

[filter]
judge = "keep the good ones"

[source.g]
kind = "llm"
prompt = "write {n} examples"
count = 5
"#,
            "mix.toml",
        )
        .unwrap();
        assert_eq!(m.llm.endpoint, "http://127.0.0.1:9000/v1");
        assert_eq!(m.llm.model, "qwen");
        assert_eq!(m.llm.temperature, 1.2);
        // defaults survive alongside the overrides
        assert_eq!(m.llm.retries, Llm::default().retries);
        assert_eq!(m.sources[0].kind, SourceKind::Llm);
        assert_eq!(m.sources[0].filters.judge, "keep the good ones");
        assert_eq!(m.sources[0].filters.judge_expect, "yes");
    }

    #[test]
    fn an_llm_source_needs_a_prompt_but_no_path() {
        let err = parse("[source.g]\nkind = \"llm\"\ncount = 5\n", "mix.toml")
            .err()
            .unwrap();
        assert!(err.contains("has no prompt"), "{err}");
        assert!(parse("[source.g]\nkind = \"llm\"\nprompt = \"go\"\n", "mix.toml").is_ok());
    }

    /// The shipped mixtures must parse, and their wrapped prompts must come out
    /// as flowing text — a broken line continuation would feed the model stray
    /// newlines and indentation.
    #[test]
    fn the_shipped_mixtures_parse() {
        for (name, text) in [
            ("pretrain.toml", include_str!("../../mixes/pretrain.toml")),
            ("assistant_sft.toml", include_str!("../../mixes/assistant_sft.toml")),
            ("assistant_llm.toml", include_str!("../../mixes/assistant_llm.toml")),
            ("assistant_qa.toml", include_str!("../../mixes/assistant_qa.toml")),
        ] {
            let m = parse(text, name).unwrap_or_else(|e| panic!("{e}"));
            assert!(!m.sources.is_empty(), "{name} has no sources");
            for src in &m.sources {
                if src.kind != SourceKind::Llm {
                    continue;
                }
                assert!(src.prompt.contains("{n}"), "{}: prompt lost {{n}}", src.name);
                assert!(
                    !src.prompt.contains("  "),
                    "{}: wrapped prompt kept its indentation: {:?}",
                    src.name,
                    src.prompt
                );
                assert!(
                    !src.system.contains('\n') || src.system.lines().count() <= 2,
                    "{}: system prompt did not join: {:?}",
                    src.name,
                    src.system
                );
            }
        }
    }

    #[test]
    fn sizes_take_suffixes() {
        assert_eq!(parse_size("4096"), Some(4096));
        assert_eq!(parse_size("64k"), Some(64_000));
        assert_eq!(parse_size("2M"), Some(2_000_000));
        assert_eq!(parse_size("unlimited"), Some(usize::MAX));
        assert_eq!(parse_size("lots"), None);
    }
}
